### ISSUE TITLE
登录后回调到登录页

### ISSUE THREAD

**Issue by chen-can** [wildfirechat/uni-h5-chat#1]
<img width="504" alt="image" src="https://github.com/wildfirechat/uni-h5-chat/assets/35422769/3a7441bb-5e7f-4e38-b6cf-9a56fa4d1345">
使用自己的域名

**Comment by imndx** [comment]
这个项目算是 web 端，需要使用 `web sdk`，`web sdk`是需要付费的，默认只能连到官方服务。

需要申请试用`web sdk` 和 `专业版 im-server`才可以，申请试用，请看[这儿](https://docs.wildfirechat.cn/trial/)
