### ISSUE TITLE
聊天没法发送视频

### ISSUE THREAD

**Issue by kenton-hu** [wildfirechat/uni-h5-chat#3]
1.点击+号，弹出框里点击相册，只能选择图片，无法选择视频
2.点击+好，弹出框里点击拍摄，可以拍摄视频，但是发出去的视频无法预览
![b7b07e03de5a31a62c87b13f9ec4e7b](https://github.com/wildfirechat/uni-h5-chat/assets/10606844/5cec71ba-7bb5-4208-a5ec-de78093ce30a)

**Comment by imndx** [comment]
> 弹出框里点击相册，只能选择图片，无法选择视频

这个问题是 uniapp 的限制，只能选视频，或者选图片，不能同时选取；

目前，将扩展改成了照片和视频，以便区分
